### ISSUE TITLE
You forgot to add the morseToString() to the description pypi.org/project/morse3/

### ISSUE THREAD

**Issue by nasirusman** [Aayush9029/encodeDecode#2]
You forgot to add the morseToString() to the description pypi.org/project/morse3/

>>> m("-.-. .- -. -.. -.--")
<morse3.Morse object at 0x0000022D58A1EC70>

Where it should be

>>> m("-.-. .- -. -.. -.--").morseToString()
'candy'

Thank you for making this library, very helpful

**Comment by Aayush9029** [comment]
Sweet. I'll take a look
